/**
 * Unit tests for the GitHub comment generation module
 */
import { describe, expect, it } from "vitest";
import {
  generateGitHubComment,
} from "../lib/github-comment.mjs";

describe("generateGitHubComment", () => {
  const baseTestRunData = {
    runId: "test-run-123",
    status: "passed",
    totalTests: 3,
    passedTests: 3,
    failedTests: 0,
    skippedTests: 0,
    duration: 5000,
    platform: "linux",
    branch: "main",
    commit: "abc123",
  };

  it("should generate a valid comment without testRunUrl", () => {
    const comment = generateGitHubComment(baseTestRunData, []);
    expect(comment).toContain("TestDriver Test Results");
    expect(comment).toContain("PASSED");
    expect(comment).toContain("3 passed");
    expect(comment).toContain("Generated by [TestDriver]");
    // Should not contain a broken link when testRunUrl is undefined
    expect(comment).not.toContain("undefined");
  });

  it("should generate a comment with testRunUrl when provided", () => {
    const testRunData = {
      ...baseTestRunData,
      testRunUrl: "https://console.testdriver.ai/runs/456",
    };
    const comment = generateGitHubComment(testRunData, []);
    expect(comment).toContain("https://console.testdriver.ai/runs/456");
    expect(comment).toContain("View Full Test Run");
  });

  it("should not include testRunUrl link when testRunUrl is undefined", () => {
    const comment = generateGitHubComment(baseTestRunData, []);
    expect(comment).not.toContain("View Full Test Run");
  });

  it("should show failure status with failed tests", () => {
    const failedTestRunData = {
      ...baseTestRunData,
      status: "failed",
      passedTests: 1,
      failedTests: 2,
    };
    const testCases = [
      {
        testName: "test one",
        testFile: "test.mjs",
        status: "failed",
        duration: 1000,
        errorMessage: "Element not found",
      },
    ];
    const comment = generateGitHubComment(failedTestRunData, testCases);
    expect(comment).toContain("FAILED");
    expect(comment).toContain("2 failed");
    expect(comment).toContain("Failures");
    expect(comment).toContain("Element not found");
  });

  it("should include test results table with test cases", () => {
    const testCases = [
      {
        testName: "my test",
        testFile: "myfile.test.mjs",
        status: "passed",
        duration: 2000,
      },
    ];
    const comment = generateGitHubComment(baseTestRunData, testCases);
    expect(comment).toContain("Test Results");
    expect(comment).toContain("my test");
    expect(comment).toContain("myfile.test.mjs");
  });

  it("should include run ID in footer", () => {
    const comment = generateGitHubComment(baseTestRunData, []);
    expect(comment).toContain("test-run-123");
  });
});
