# Ensure that the published `testdriverai` package is installable on multiple version of Node.js across multiple operating systems.
name: VSCode Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-vscode-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VSCode Build + Publish
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: testdriverai/vscode
          event-type: cli-publish
          token: ${{ secrets.GITHUB_TOKEN }}
