/**
 * Airbnb Search Test
 * - Loads Airbnb
 * - Searches for places in Austin, TX
 * - Sets dates from Feb 2 to Feb 20
 * - Sets 2 guests
 * 
 * Generated by TestDriver MCP Server
 */
import { describe, expect, it } from "vitest";
import { TestDriver } from "../lib/vitest/hooks.mjs";

describe("Airbnb Austin Search", () => {
  it("should search for places in Austin, TX for 2 people from Feb 2 to Feb 20", async (context) => {
    const testdriver = TestDriver(context);

    // --- GENERATED COMMANDS ---
    await testdriver.provision.chrome({ url: "https://www.airbnb.com" });

    await testdriver.find("Where search input field or destination input").click();

    await testdriver.type("Austin, TX");

    await testdriver.find("Austin, Texas suggestion in the dropdown").click();

    await testdriver.find("February 2 or the number 2 in the February 2026 calendar").click();

    await testdriver.find("February 20 or the number 20 in the February 2026 calendar").click();

    await testdriver.find("Who button or Add guests section").click();

    await testdriver.find("Plus button or increase button for Adults").click();

    await testdriver.find("Plus button or increase button for Adults").click();

    await testdriver.find("Search button with magnifying glass icon").click();

    const assertResult = await testdriver.assert("Search results are showing Airbnb listings in Austin, Texas for the selected dates");
    expect(assertResult).toBeTruthy();

    // --- END GENERATED ---
  }, 120000); // 2 minute timeout for this test
});
