/**
 * Automated test that navigates to Airbnb and searches for a property in Austin, TX for 2 people from February 2-20
 * Generated by TestDriver MCP Server
 */
import { describe, expect, it } from "vitest";
import { TestDriver } from "testdriverai/lib/vitest/hooks.mjs";

describe("Airbnb Austin Booking Search", () => {
  it("Automated test that navigates to Airbnb and searches for a property in Austin, TX for 2 people from February 2-20", async (context) => {
    const testdriver = TestDriver(context);

    // --- GENERATED COMMANDS ---
    await testdriver.provision.chrome({ url: "https://www.airbnb.com" });

    await testdriver.find("the \"Where\" search input field with placeholder \"Search destinations\"").click();

    await testdriver.type("Austin, TX");

    await testdriver.find("the \"When\" date picker button showing \"Add dates\"").click();

    await testdriver.wait(2000);

    await testdriver.find("February 2 date in the calendar picker").click();

    await testdriver.find("February 20 in the calendar").click();

    await testdriver.find("Who Add guests button").click();

    await testdriver.wait(2000);

    await testdriver.find("plus button to add adults next to the number 0").click();

    await testdriver.find("plus button to add adults").click();

    await testdriver.find("Search button").click();

    // --- END GENERATED ---
  });
});
