name: TestDriver Tests with GitHub Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      # Required for posting comments on PRs
      pull-requests: write
      # Required for posting comments on commits
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TestDriver tests
        env:
          # TestDriver API key (add this to your repository secrets)
          TD_API_KEY: ${{ secrets.TD_API_KEY }}
          
          # GitHub token for posting comments (automatically provided)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # PR number for PR comments
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          
          # Git information (automatically available)
          # GITHUB_SHA, GITHUB_REF_NAME, GITHUB_REPOSITORY, GITHUB_ACTOR
          
        run: npm run test:sdk
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-report.junit.xml
            test-results/
          retention-days: 30
      
      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ TestDriver tests failed. Check the workflow logs for details.'
            })
